const TALLERES_MOCK = [
  {
    nombre: "Juan Pérez",
    telefono: "+54 9 11 0000 1111",
    direccion: "Av. Colón 123, Córdoba",
    horarioAtencion: "Lun-Vie 09:00-17:00",
    rubro: "Carpintería",
    redSocial: "https://instagram.com/juan.carpintero",
    email: "juan@example.com",
    nombreTaller: "El Serrucho Loco",
    descripcion: "Taller de muebles artesanales",
    autorizado: true,
    latitud: -31.4167,
    longitud: -64.1833,
  },
  {
    nombre: "Lucía García",
    telefono: "+54 9 11 2222 3333",
    direccion: "General Paz 456, Córdoba",
    horarioAtencion: "Sábados 10:00-14:00",
    rubro: "Pintura",
    redSocial: "https://instagram.com/lucia.arte",
    email: "lucia@example.com",
    nombreTaller: "Pinceladas Reales",
    descripcion: "Clases de óleo y acuarela",
    autorizado: true,
    latitud: -31.413,
    longitud: -64.181,
  },
];
